/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Aluno;
import classes.Reserva;
import classes.UsuarioLogado;
import enums.Status;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static telas.TelaInicial.listaReservas;

public class PerfilUsuario extends javax.swing.JFrame {
    // instanciando um aluno logado
    private final Aluno alunoLogado;

    public PerfilUsuario() {
        initComponents();
        this.alunoLogado = (Aluno) UsuarioLogado.getUsuarioLogado();
        estadoInicial();
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("resources/gym.png"));
        this.setIconImage(icon.getImage());
        this.setTitle("Painel do aluno");
    }
    
    // função para atualizar a tabela de informações de reserva
    private void carregarTabela() {
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Aula", "Professor", "Data", "Hora", "Status"}, 0);
        modelo.setRowCount(0);
        // checando se o usuário tem reservas
        if (alunoLogado.getReservas().isEmpty()) {
            System.out.print("O usuário não tem reservas");
        }
        
        // iterando sobre cada reserva para listar elas
        for (int i = 0; i < alunoLogado.getReservas().size(); i++) {
            
            // formatando TimeStamp para dd/mm
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM");
            String dataFormatada = dateFormat.format(alunoLogado.getReservas().get(i).getAula().getData());
            // formatando TimeStamp para horas '20h15'
            SimpleDateFormat timeFormat = new SimpleDateFormat("HH'h'mm");
            String horaFormatada = timeFormat.format(alunoLogado.getReservas().get(i).getAula().getData());
            
            Object linha[] = new Object[]{
                alunoLogado.getReservas().get(i).getAula().getNome(),
                alunoLogado.getReservas().get(i).getAula().getProfessor().getNome(),
                dataFormatada,
                horaFormatada,
                alunoLogado.getReservas().get(i).getStatus()
            };
            modelo.addRow(linha);
        }

        tabela.setModel(modelo);
    }

    // inicia ou reinicia a tela em estado inicial 
    private void estadoInicial(){
        carregarTabela();
        nomePlaceholder.setText(alunoLogado.getNome());
        mensalidadeValue.setText(String.format("R$ %.2f", alunoLogado.getMensalidade()));
        unidadeValue.setText(alunoLogado.getUnidade().name());
        
        // isso está errado, está pegando todas as aulas
        int quantidadeAulas = 0;
        for (Reserva reserva : alunoLogado.getReservas()) {
            if (reserva.getStatus().equals(Status.Confirmada)) {
                quantidadeAulas += 1;
            }
        }
        aulasValue.setText(Integer.toString(quantidadeAulas));
        
        emailInput.setText(alunoLogado.getEmail());
        celularInput.setText(alunoLogado.getCelular());
        nomeInput.setText(alunoLogado.getNome());
        senhaInput.setText("");
        botaoEditar.setEnabled(false);
        botaoExcluirReserva.setEnabled(false);
        botaoConfirmarReserva.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ola = new javax.swing.JLabel();
        nomePlaceholder = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        mensalidadeLabel = new javax.swing.JLabel();
        aulasLabel = new javax.swing.JLabel();
        unidadeLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        infoTitle = new javax.swing.JLabel();
        celularLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        senhaLabel = new javax.swing.JLabel();
        mensalidadeValue = new javax.swing.JLabel();
        aulasValue = new javax.swing.JLabel();
        unidadeValue = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        celularInput = new javax.swing.JTextField();
        nomeInput = new javax.swing.JTextField();
        senhaInput = new javax.swing.JTextField();
        botaoEditar = new javax.swing.JButton();
        aulaLabel = new javax.swing.JLabel();
        aulasPanel = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        botaoBuscarAulas = new javax.swing.JButton();
        botaoExcluirReserva = new javax.swing.JButton();
        botaoConfirmarReserva = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Logout = new javax.swing.JMenu();
        buscarAulas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 480));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ola.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        ola.setText("Olá,");

        nomePlaceholder.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        nomePlaceholder.setText("[aluno]");

        infoPanel.setBackground(new java.awt.Color(250, 250, 250));
        infoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        infoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("Suas informações atuais");

        mensalidadeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mensalidadeLabel.setText("Mensalidade:");

        aulasLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aulasLabel.setText("Aulas participadas:");

        unidadeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        unidadeLabel.setText("Sua unidade atual:");

        emailLabel.setText("Email:");

        infoTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        infoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoTitle.setText("Informações pessoais");

        celularLabel.setText("Celular:");

        nomeLabel.setText("Nome:");

        senhaLabel.setText("Senha:");

        mensalidadeValue.setText("[mensalidade]");

        aulasValue.setText("[aulas]");

        unidadeValue.setText("[unidade]");

        emailInput.setText("[email]");

        celularInput.setText("[celular]");

        nomeInput.setText("[nome]");

        senhaInput.setText("[senha]");
        senhaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                senhaInputKeyTyped(evt);
            }
        });

        botaoEditar.setText("Alterar informações");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(botaoEditar)
                    .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(aulasLabel)
                                    .addComponent(unidadeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aulasValue)
                                    .addComponent(unidadeValue)))
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(mensalidadeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mensalidadeValue)))
                        .addGap(124, 124, 124))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(emailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailInput))
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(celularLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(celularInput))
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(nomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeInput))
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(senhaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(senhaInput)))
                        .addContainerGap())))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensalidadeLabel)
                    .addComponent(mensalidadeValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aulasLabel)
                    .addComponent(aulasValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadeLabel)
                    .addComponent(unidadeValue))
                .addGap(18, 18, 18)
                .addComponent(infoTitle)
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celularLabel)
                    .addComponent(celularInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaLabel)
                    .addComponent(senhaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoEditar)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        aulaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        aulaLabel.setText("Veja suas próximas aulas!");

        aulasPanel.setBackground(new java.awt.Color(250, 250, 250));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Aula", "Professor", "Data", "Hora", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        aulasPanel.setViewportView(tabela);

        botaoBuscarAulas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoBuscarAulas.setText("Buscar aulas");
        botaoBuscarAulas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoBuscarAulasMouseClicked(evt);
            }
        });

        botaoExcluirReserva.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoExcluirReserva.setText("Excluir");
        botaoExcluirReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoExcluirReservaMouseClicked(evt);
            }
        });
        botaoExcluirReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirReservaActionPerformed(evt);
            }
        });

        botaoConfirmarReserva.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoConfirmarReserva.setText("Confirmar");
        botaoConfirmarReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoConfirmarReservaMouseClicked(evt);
            }
        });
        botaoConfirmarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoBuscarAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoConfirmarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoExcluirReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(aulasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomePlaceholder))
                    .addComponent(aulaLabel))
                .addGap(501, 501, 501))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ola)
                            .addComponent(nomePlaceholder))
                        .addGap(18, 18, 18)
                        .addComponent(aulaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(aulasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoBuscarAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoExcluirReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoConfirmarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(Logout);

        buscarAulas.setText("Buscar aulas");
        buscarAulas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarAulasMouseClicked(evt);
            }
        });
        jMenuBar1.add(buscarAulas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senhaInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaInputKeyTyped
        botaoEditar.setEnabled(true);
    }//GEN-LAST:event_senhaInputKeyTyped

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        // recuperando os valores de cada input
        String senha = senhaInput.getText();
        String email = emailInput.getText();
        String celular = celularInput.getText();
        String nome = nomeInput.getText();
        
        // checando formatação do celular e do email
        if (!celular.matches("\\d{11}") || !email.contains("@")){
            JOptionPane.showMessageDialog(this, "Insira celular e/ou email válidos!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        // validar senha para poder alterar as informações
        else if (alunoLogado.validarSenha(senha)) {
            alunoLogado.setNome(nome);
            alunoLogado.setEmail(email);
            alunoLogado.setCelular(celular);
            JOptionPane.showMessageDialog(this, "Informações editadas com sucesso", "Info", JOptionPane.INFORMATION_MESSAGE);
            estadoInicial();
        } else {
            JOptionPane.showMessageDialog(this, "Senha não confere!", "Erro", JOptionPane.ERROR_MESSAGE);
            estadoInicial();
        }
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        UsuarioLogado.limparSessao();
        TelaInicial tela = new TelaInicial();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void buscarAulasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarAulasMouseClicked
       CriarReserva tela = new CriarReserva();
       tela.setVisible(true);
    }//GEN-LAST:event_buscarAulasMouseClicked

    private void botaoBuscarAulasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBuscarAulasMouseClicked
       CriarReserva tela = new CriarReserva();
       tela.setVisible(true);
    }//GEN-LAST:event_botaoBuscarAulasMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        carregarTabela();
    }//GEN-LAST:event_formWindowGainedFocus

    private void botaoExcluirReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoExcluirReservaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoExcluirReservaMouseClicked

    private void botaoExcluirReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirReservaActionPerformed
    int linhaSelecionada = tabela.getSelectedRow();
    
    if (linhaSelecionada >= 0) {
        Reserva reserva = alunoLogado.getReservas().get(linhaSelecionada);
        listaReservas.remove(reserva);
        reserva.getAula().getReservas().remove(reserva);
        alunoLogado.getReservas().remove(linhaSelecionada);
        JOptionPane.showMessageDialog(null, "Reserva removida", "Info", JOptionPane.INFORMATION_MESSAGE);
        tabela.clearSelection();
        
    }
    estadoInicial();
    }//GEN-LAST:event_botaoExcluirReservaActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        botaoExcluirReserva.setEnabled(true);
        botaoConfirmarReserva.setEnabled(true);
    }//GEN-LAST:event_tabelaMouseClicked

    private void botaoConfirmarReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarReservaMouseClicked
        int linhaSelecionada = tabela.getSelectedRow();
        
        if (linhaSelecionada >= 0) {
            Reserva reserva = alunoLogado.getReservas().get(linhaSelecionada);
            reserva.setStatus(Status.Confirmada);
            JOptionPane.showMessageDialog(null, "Reserva confirmada!", "Info", JOptionPane.INFORMATION_MESSAGE);
            tabela.clearSelection();
        }
        estadoInicial();
    }//GEN-LAST:event_botaoConfirmarReservaMouseClicked

    private void botaoConfirmarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoConfirmarReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Logout;
    private javax.swing.JLabel aulaLabel;
    private javax.swing.JLabel aulasLabel;
    private javax.swing.JScrollPane aulasPanel;
    private javax.swing.JLabel aulasValue;
    private javax.swing.JButton botaoBuscarAulas;
    private javax.swing.JButton botaoConfirmarReserva;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluirReserva;
    private javax.swing.JMenu buscarAulas;
    private javax.swing.JTextField celularInput;
    private javax.swing.JLabel celularLabel;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel infoTitle;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensalidadeLabel;
    private javax.swing.JLabel mensalidadeValue;
    private javax.swing.JTextField nomeInput;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel nomePlaceholder;
    private javax.swing.JLabel ola;
    private javax.swing.JTextField senhaInput;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JTable tabela;
    private javax.swing.JLabel unidadeLabel;
    private javax.swing.JLabel unidadeValue;
    // End of variables declaration//GEN-END:variables
}
